services:
  localstack:
    container_name: localstack
    image: localstack/localstack:4.3.0
    ports:
      - "4566:4566"            # LocalStack Gateway      
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - PERSISTENCE=1
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=dynamodb,sqs,sns,s3,lambda
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" 