[GLOBAL]
pants_version = "2.17.0"
plugins = [
    "pantsbuild.pants.contrib.go",
    "pantsbuild.pants.contrib.node",
    "pantsbuild.pants.contrib.dotnet",
]

[source]
root_patterns = [
    "backend",
    "frontend",
    "infrastructure",
]

[python]
interpreter_constraints = [">=3.8"]

[node]
package_manager = "npm"
version = "10.2.4"

[dotnet]
version = "8.0"
build_configuration = "Debug"
output_dir = "dist"
restore_args = ["--no-cache"]
build_args = ["--configuration", "Debug", "--no-restore"]
publish_args = ["--configuration", "Release", "--no-restore"]
project_root = "backend"
project_file = "backend.csproj"

[test]
report = true 